package TicketPackage.PassengerPackage;

import java.io.Serializable;

/**
 * //TODO - Project Description
 * @author Ciaran O'Boyle
 * Created on: 25/11/2020
 * Updated on: 08/12/2020
 * AirportCheckIn:TicketPackage.PassengerPackage:Passenger
 */
public abstract class Passenger implements Serializable {
    private static int numberOfPassengers = 0;
    private String seat, firstName, lastName;
    private int ticketNumber;
    private String departureDate;

    /**
     * This method sets the passenger's seat
     * @param passengerSeat the String containing the passenger's seat
     */
    public void setSeat(String passengerSeat){
        seat=passengerSeat;
    }//setSeat

    /**
     * This method sets the Passenger's name to a new value
     * @param passengerFirstName the passenger's first name
     */
    public void setFirstname(String passengerFirstName){
        firstName=passengerFirstName;
    }//setFirstName

    /**
     *
     * @param passengerLastname
     */
    public void setLastname(String passengerLastname){
        lastName=passengerLastname;
    }//SetLastName

    /**
     *
     * @param passengerTicketNumber
     */
    public void setTicketNumber(int passengerTicketNumber){
        ticketNumber=passengerTicketNumber;
    }//setTicketNumber

    /**
     *
     * @param passengerDepartureDate
     */
    public void setDepartureDate(String passengerDepartureDate){
        departureDate=passengerDepartureDate;
    }//setDepartureDate

    /**
     *
     * @param numberOfPassengers
     */
    public static void setNumberOfPassengers(int numberOfPassengers) {
        //Autogenerated - do not want to mess with in case of breaking
        Passenger.numberOfPassengers = numberOfPassengers;
    }//setNumberOfPassengers

    /**
     * This method gets the passengers seat number
     * @return A string containing the passenger's chosen seat
     */
    public String getSeat() {
        return seat;
    }//getSeat

    /**
     *
     * @return
     */
    public String getFirstName(){
        return firstName;
    }//getFirstName

    /**
     *
     * @return
     */
    public String getLastname(){
        return lastName;
    }//getLastName

    /**
     *
     * @return
     */
    public int getTicketNumber(){
        return ticketNumber;
    }//getTicketNumber

    /**
     *
     * @return
     */
    public String getDepartureDate(){
        return departureDate;
    }

    /**
     *
     * @return
     */
    public static int getNumberOfPassengers(){
        return numberOfPassengers;
    }//getNumberOfPassengers

    /**
     *
     */
    protected static void addPassenger(){
        Passenger.numberOfPassengers++;
    }//addPassenger

    /**
     *
     */
    public void showAllDetails(){
        System.out.println("* * * START * * *");
        System.out.println("The seat reference is:        " + seat);
        System.out.println("The passenger first name is:  " + firstName);
        System.out.println("The passenger last name is:   " + lastName);
        System.out.println("The ticket number is:         " + ticketNumber);
        System.out.println("The departure date is:         " + departureDate);
        System.out.println("* * * END * * *");
    }//showAllDetails
}//Passenger
